#define BUFFERSIZE 256

char* TITLE="BDialog";
char* ICON_NAME = "BDialog";

//Can be DIALOG / DOCK / MENU / TOOLBAR
char* WINDOW_TYPE = "DIALOG";

unsigned int VERTICAL_PADDING = 16;
unsigned int HORIZONTAL_PADDING = 48;
unsigned int BUTTON_PADDING = 8;
unsigned int BUTTON_MARGIN = 4;
unsigned int BUTTON_VERTICAL_MARGIN = 2;
unsigned int BORDER_RADIUS = 4;
unsigned int BORDER_THICKNESS = 0;
unsigned int BUTTON_MIN_WIDTH = 50;

int X = -1;
int Y = -1;

// 0 (Left) 1 (Center) 2 (Right)
unsigned int BUTTON_POSITION = 2;
double LINE_HEIGHT = 1.35;
unsigned int DEFAULT_LINES = 2;

char* BACKGROUND_COLOR = "#FFFFFF";
char* FOREGROUND_COLOR = "#000000";

char* BUTTON_BACKGROUND_COLOR = "#EFEFEF";
char* BUTTON_HOVER_BACKGROUND_COLOR = "#DDDDDD";
char* BUTTON_FOREGROUND_COLOR = "#000000";

char* BUTTON_YES_BACKGROUND_COLOR = "#7eed00";
char* BUTTON_YES_HOVER_BACKGROUND_COLOR = "#78dd04";
char* BUTTON_YES_FOREGROUND_COLOR = "#000000";

char* BUTTON_NO_BACKGROUND_COLOR = "#F03D43";
char* BUTTON_NO_HOVER_BACKGROUND_COLOR = "#EC3F45";
char* BUTTON_NO_FOREGROUND_COLOR = "#000000";

char* BUTTON_BORDER_COLOR = "#DDDDDD";

char* FONT_NAME = "Arial";
double FONT_SIZE = 16;
